repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.4
    hooks:
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-xml
    -   id: check-yaml
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: file-contents-sorter
        files: .gitignore
    -   id: trailing-whitespace
-   repo: git://github.com/pre-commit/mirrors-fixmyjs
    sha: v2.0.0
    hooks:
    -   id: fixmyjs
-   repo: git://github.com/pre-commit/mirrors-jshint
    sha: v2.9.5
    hooks:
    -   id: jshint
    # TODO: set "unused": to true
