version: 2

jobs:
  lint:
    docker:
      - image: python:3.7.1
    steps:
      - checkout
      - run: pip install pre-commit
      - restore_cache:
          keys:
            - cache-pre-commit-{{ checksum ".pre-commit-config.yaml" }}
      - run: pre-commit install-hooks
      - save_cache:
          key: cache-pre-commit-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache/pre-commit
      - run: pre-commit run --all-files

  build:
    docker:
      - image: debian:jessie
    steps:
      - run: apt-get update
      - run: apt-get install -qy gettext libglib2.0-dev make zip
      - checkout
      - run: make build

workflows:
  version: 2
  run-jobs:
    jobs:
      - lint
      - build
