version: 2.1

orbs:
  linter: thekevjames/linter@0

jobs:
  build:
    docker:
      - image: debian:jessie
    steps:
      - run: apt-get update
      - run: apt-get install -qy gettext libglib2.0-dev make zip
      - checkout
      - run: make build

workflows:
  run-jobs:
    jobs:
      - linter/pre-commit:
          python_version: 3.7.4
      - build
